[project]
name = "rna-struct-diff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "biopandas>=0.5.2",
    "biopython>=1.88",
    "biotite>=1.6.0",
    "cpdb-protein>=0.2.1",
    "dllogger",
    "dotenv>=0.9.9",
    "e3nn>=0.6.0",
    "lovely-tensors>=0.1.22",
    "matplotlib>=3.11.1",
    "mdanalysis>=2.10.0",
    "plotly>=7.0.0",
    "polars>=1.44.1",
    "pyarrow>=25.0.1",
    "pynvml==11.0.0",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "torch>=2.14.0",
    "tqdm>=4.70.1",
    "wandb>=0.30.0",
]

[tool.uv.sources]
dllogger = { git = "https://github.com/NVIDIA/dllogger" }
